### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/degit/dist/help.md'

### ISSUE THREAD

**Issue by moop-moop** [Rich-Harris/degit#169]
On Fedora 31, standard install of `npm install -g degit`

nodejs v12.15.0

```bash
[vagrant@localhost ~]$ which degit
/usr/local/bin/degit
[vagrant@localhost ~]$ ls -l /usr/local/bin/degit
lrwxrwxrwx. 1 root root 32 Feb 19 15:03 /usr/local/bin/degit -> ../lib/node_modules/degit/bin.js
[vagrant@localhost ~]$ degit --help
(node:2423) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/degit/dist/help.md'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at main (/usr/local/lib/node_modules/degit/dist/bin.js:5514:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/degit/dist/bin.js:5627:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
(node:2423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Version 2.6.0 doesn't have the error.

**Comment by Rich-Harris** [comment]
ah, whoops. I know why this happened — should get a chance to fix it later today

**Comment by jrop** [comment]
I am getting the following error in degit@2.8.0:

```
❯ degit --help
(node:57494) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/jonathan/.config/nvm/10.17.0/lib/node_modules/degit/dist/help.md'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at main (/Users/jonathan/.config/nvm/10.17.0/lib/node_modules/degit/dist/bin.js:5514:5)
    at Object.<anonymous> (/Users/jonathan/.config/nvm/10.17.0/lib/node_modules/degit/dist/bin.js:5627:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
(node:57494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by assoft** [comment]
I have the same problem. Is there anyone to deal with this?

**Comment by RuAnDe** [comment]
@assoft
Sorry my bad english.

The file lies on the directory above @jrop already made a request for fix [pull 179](https://github.com/Rich-Harris/degit/pull/179).
Although it might be better to copy the file to dist.

**Comment by keerthivasan-r** [comment]
Instead of code change, can we move the `help.md` file into `dist` directory during build. we can leverage `rollup-plugin-copy` for copying the help.md. What do you think? we will definitely need this feature

`plugins: [
    copy({
      targets: [
        { src: 'help.md', dest: 'dist' }
      ]
    })
  ]`

Let me know, I can give a PR

**Comment by TMorgan99** [comment]
I'm getting this too.
It appears the help.md is not in the right place.
As a workaround, just avoid using the --help option.

**Comment by davclark** [comment]
This still appears to be an issue?

**Comment by nake89** [comment]
This issue among others are fixed in community driven fork https://github.com/tiged/tiged. :slightly_smiling_face: More info here: https://github.com/Rich-Harris/degit/issues/258
Maintainers (and stars) welcome. :blush:

**Comment by YogliB** [comment]
Thanks for the report. I verified this against the latest release (3.6.6) and `degit --help` now works from both local and global installs. The help file has moved to `assets/help.md` and ships with the package, so the original `ENOENT: dist/help.md` error is resolved.
