### ISSUE TITLE
degit --help => error, because of wrong path to help.md

### ISSUE THREAD

**Issue by aisbergde** [Rich-Harris/degit#263]
From the documentation I should be able to execute
`degit --help`
But when I do this, I get an error:

```
C:\Users\ggoer>degit --help
node:fs:497
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:\Users\ggoer\AppData\Roaming\npm\node_modules\degit\dist\help.md'
    at Object.openSync (node:fs:497:3)
    at Object.readFileSync (node:fs:393:35)
    at main (C:\Users\ggoer\AppData\Roaming\npm\node_modules\degit\dist\bin.js:5514:5)
    at Object.<anonymous> (C:\Users\ggoer\AppData\Roaming\npm\node_modules\degit\dist\bin.js:5627:1)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\ggoer\\AppData\\Roaming\\npm\\node_modules\\degit\\dist\\help.md'
}
```

Windows 10

this is the wrong path:
'C:\Users\ggoer\AppData\Roaming\npm\node_modules\degit\dist\help.md'
the right path would be:
'C:\Users\ggoer\AppData\Roaming\npm\node_modules\degit\help.md'

**Comment by icflorescu** [comment]
It's an old, well-known problem. See #258. You might want to use the community driven fork available at https://github.com/tiged/tiged.

**Comment by gucal** [comment]
Haven't found a clear solution yet? I keep getting the same error. Should we continue on `tiged`?

**Comment by xyy94813** [comment]
Hi, @icflorescu 

This repo has not been maintained for a long time.
Would you consider "archiving" ?

**Comment by YogliB** [comment]
issue seems to be resolved, please open a new issue if it's still an issue.
thanks for reporting!
