### ISSUE TITLE
Error: Cannot find module 'sander' when running 'degit'

### ISSUE THREAD

**Issue by heardy** [Rich-Harris/degit#34]
I followed the getting started guide (https://sapper.svelte.technology/guide#getting-started) but running `degit` returns an error.

After running `npm install -g degit ` as per the above guide, I ran `degit sveltejs/sapper-template my-app` and get the following error.

```
kevin.heard ~/git $ degit sveltejs/sapper-template my-app
module.js:549
    throw err;
    ^

Error: Cannot find module 'sander'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kevin.heard/.nvm/versions/node/v8.10.0/lib/node_modules/degit/index.js:11:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I noticed that `sander` is in `devDependencies`, which it looks like it should be in `dependencies`?

**Comment by Rich-Harris** [comment]
whoops! this was broken in 2.1, but it went undetected because sander was listed as a dev dependency already. Fixed in 2.1.3! thanks
